name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # -----------------
  # Lint + Test
  # -----------------
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744     # v4.1.4 SHA
      - uses: actions/setup-node@9369e68b33a08e6bda68467b8642e5a8b6a2493d   # v5.0.0 SHA
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm test

  # -----------------
  # Dependency Review
  # -----------------
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - name: Run npm audit
        run: npm audit --production --audit-level=moderate || true
      - name: GitHub Dependency Review
        uses: actions/dependency-review-action@c9733906b4af3ebdac38128c549682a8085e9086 # v4.2.5 SHA

  # -----------------
  # CodeQL Scan
  # -----------------
  codeql:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - name: Initialize CodeQL
        uses: github/codeql-action/init@5e7b7b89ecffb9a89bf2429fa8e95b646c8e3b6a    # v3.26.8 SHA
        with:
          languages: javascript
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@5e7b7b89ecffb9a89bf2429fa8e95b646c8e3b6a  # v3.26.8 SHA

  # -----------------
  # Codacy Scan
  # -----------------
  codacy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - name: Run Codacy Analysis
        uses: codacy/codacy-analysis-cli-action@2425f71abea87f34a06e76e6a79171b61d14cfd8 # master SHA as of Oct 2025
        with:
          api-token: ${{ secrets.CODACY_API_TOKEN }}
          tool: eslint
          format: sarif
          output: results.sarif
      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@5e7b7b89ecffb9a89bf2429fa8e95b646c8e3b6a   # v3.26.8 SHA
        with:
          sarif_file: results.sarif

  # -----------------
  # SonarQube
  # -----------------
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@26c5182dea89a1d0ace21e671b12b3b4662a69d3 # v4.2.0 SHA
        with:
          args: -Dsonar.login=${{ secrets.SONAR_TOKEN }}