name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # -----------------
  # Test
  # -----------------
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm test

  # -----------------
  # CodeQL Scan
  # -----------------
  codeql:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  # -----------------
  # Codacy Scan
  # -----------------
  # Need to learn and add
  # -----------------
  # SonarQube
  # -----------------
  sonarqube:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # only run on main branch
    steps:
      - uses: actions/checkout@v4.1.4
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2.2
        with:
          args: -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          SONAR_HOST_URL: https://sonarcloud.io
