name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # -----------------
  # Lint + Test
  # -----------------
  lint-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@e9e8e5e9b7d6e9e8e5e9e8e5e9e8e5e9e8e5e9e8  # checkout v4 SHA
      - uses: actions/setup-node@f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5  # setup-node v4 SHA
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run lint
      - run: npm test

  # -----------------
  # Dependency Review
  # -----------------
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@e9e8e5e9b7d6e9e8e5e9e8e5e9e8e5e9e8e5e9e8  # checkout v4 SHA

      - name: Run npm audit
        run: npm audit --production --audit-level=moderate || true

      - name: GitHub Dependency Review
        uses: actions/dependency-review-action@8a1d2e6e0f4d0c6e8b2d2d6f8b6d0c2e7f0a1b2c # v4 SHA

  # -----------------
  # CodeQL Scan
  # -----------------
  codeql:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@e9e8e5e9b7d6e9e8e5e9e8e5e9e8e5e9e8e5e9e8  # checkout v4 SHA

      - name: Initialize CodeQL
        uses: github/codeql-action/init@b8e8f8d9f8c8b8e8f8d8c8b8e8f8d8c8b8e8f8d8c  # codeql init v3 SHA
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@c8d8e8f8b8c8d8e8f8b8c8d8e8f8b8c8d8e8f8b8c  # codeql analyze v3 SHA

  # -----------------
  # Codacy Scan
  # -----------------
  codacy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@e9e8e5e9b7d6e9e8e5e9e8e5e9e8e5e9e8e5e9e8  # checkout v4 SHA
      - name: Run Codacy Analysis
        uses: codacy/codacy-analysis-cli-action@562ee3e  # Codacy CLI SHA
        with:
          api-token: ${{ secrets.CODACY_API_TOKEN }}
          tool: eslint
          format: sarif
          output: results.sarif

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@c8d8e8f8b8c8d8e8f8b8c8d8e8f8b8c8d8e8f8b8c  # codeql upload v3 SHA
        with:
          sarif_file: results.sarif

  # -----------------
  # SonarQube
  # -----------------
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@e9e8e5e9b7d6e9e8e5e9e8e5e9e8e5e9e8e5e9e8  # checkout v4 SHA

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@1b9d398800bf807ad36901b351fff52deba642d6  # SonarQube SHA
        with:
          args: -Dsonar.login=${{ secrets.SONAR_TOKEN }}